export const ADD_INGREDIENT = 'ADD_INGREDIENTS';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENTS';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHSE_BURGER_SUCCESS = 'PURCHSE_BURGER_SUCCESS';
export const PURCHSE_BURGER_FAIL = 'PURCHSE_BURGER_FAIL';